"""Step 9, part 2 (local CPU): export the published numbers the demo page
plots next to its live runs.

Reads results/data/corruption_outputs.npz and test_outputs.npz and writes
one TypeScript module into the portfolio with, per corruption and severity:
accuracy with a bootstrap 95% CI, mean normalized confidence, the
confidence-minus-accuracy gap, and the paired SNN-minus-ANN accuracy
difference with its CI. Same confidence mapping as step 5 (max / sum).
Also exports the bank (33 test ids + labels) and the class names, so the
page renders its picker without waking the backend.

Usage (from the repo root):
    python scripts/step9_demo_export.py
    python scripts/step9_demo_export.py --out "path/to/spikes-demo-data.ts"
"""

import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from step9_demo_api import (BANK_IDS, BANK_LABELS, CLASS_NAMES, KINDS,  # noqa: E402
                            SEVERITIES)

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "results", "data")
DEFAULT_OUT = os.path.join("D:\\", "Projects", "Portfolio Website", "src", "lib",
                           "spikes-demo-data.ts")
N_BOOT = 3000
RNG = np.random.default_rng(0)


def confidences(out):
    s = out.sum(1, keepdims=True)
    s[s == 0] = 1e-9
    p = out / s
    return p.max(1), out.argmax(1)


def boot_ci(stat_fn, n, reps=N_BOOT):
    vals = [stat_fn(RNG.integers(0, n, n)) for _ in range(reps)]
    return float(np.percentile(vals, 2.5)), float(np.percentile(vals, 97.5))


def condition_stats(snn_out, ann_out, labels):
    n = len(labels)
    cs, ps = confidences(snn_out)
    ca, pa = confidences(ann_out)
    ok_s = (ps == labels).astype(float)
    ok_a = (pa == labels).astype(float)

    def block(ok, conf):
        acc = float(ok.mean())
        lo, hi = boot_ci(lambda idx: ok[idx].mean(), n)
        return {
            "acc": round(acc, 4), "accLo": round(lo, 4), "accHi": round(hi, 4),
            "conf": round(float(conf.mean()), 4),
            "gap": round(float(conf.mean() - acc), 4),
        }

    diff = float(ok_s.mean() - ok_a.mean())
    dlo, dhi = boot_ci(lambda idx: ok_s[idx].mean() - ok_a[idx].mean(), n)
    return {
        "snn": block(ok_s, cs),
        "ann": block(ok_a, ca),
        "diff": round(diff, 4), "diffLo": round(dlo, 4), "diffHi": round(dhi, 4),
    }


def main(out_path):
    c = np.load(os.path.join(DATA, "corruption_outputs.npz"))
    labels = c["labels"]
    n = len(labels)

    clean = condition_stats(c["snn_clean_0"], c["ann_clean_0"], labels)
    population = {}
    for kind in KINDS:
        rows = [{"level": 0, "severity": None, **clean}]
        if kind != "clean":
            for level, sev in enumerate(SEVERITIES[kind], start=1):
                rows.append({
                    "level": level, "severity": sev,
                    **condition_stats(c[f"snn_{kind}_{level}"],
                                      c[f"ann_{kind}_{level}"], labels),
                })
        population[kind] = rows
        for r in rows:
            print(f"{kind:<9} sev={str(r['severity']):<5} "
                  f"snn {r['snn']['acc']:.4f} [{r['snn']['accLo']:.3f},{r['snn']['accHi']:.3f}] "
                  f"conf {r['snn']['conf']:.3f}   "
                  f"ann {r['ann']['acc']:.4f} conf {r['ann']['conf']:.3f}   "
                  f"diff {r['diff']:+.3f} [{r['diffLo']:+.3f},{r['diffHi']:+.3f}]")

    bank = [{"index": i, "testId": tid, "label": lab}
            for i, (tid, lab) in enumerate(zip(BANK_IDS, BANK_LABELS))]

    def ts(obj):
        return json.dumps(obj, indent=2)

    body = f"""// GENERATED by D:\\Projects\\SNNs\\scripts\\step9_demo_export.py from the
// published corruption run (results/data/corruption_outputs.npz, n={n},
// single seed, bootstrap 95% CIs with {N_BOOT} resamples). Do not edit by hand.
//
// Confidence is the normalized score of the predicted class (max / sum of
// the raw rate outputs), never softmax: the models were trained with MSE on
// one-hot targets, so their outputs are rates, not logits.

export const SPIKES_N_TEST = {n}

export const SPIKES_CLASS_NAMES = {ts(CLASS_NAMES)} as const

export const SPIKES_KINDS = {ts(KINDS)} as const
export type SpikesKind = (typeof SPIKES_KINDS)[number]

/** Severity values per corruption, index 0 = level 1. Level 0 is clean. */
export const SPIKES_SEVERITIES: Record<Exclude<SpikesKind, 'clean'>, number[]> = {ts(SEVERITIES)}

/** The demo bank: 33 test samples, 3 per class, chosen where both models
 *  are right on the clean input. `testId` is the test-set index. */
export const SPIKES_BANK: {{ index: number; testId: number; label: number }}[] = {ts(bank)}

export interface SpikesModelStats {{
  acc: number
  accLo: number
  accHi: number
  conf: number
  /** mean confidence minus accuracy: positive = overconfident */
  gap: number
}}

export interface SpikesConditionStats {{
  level: number
  severity: number | null
  snn: SpikesModelStats
  ann: SpikesModelStats
  /** SNN minus ANN accuracy, paired, with its bootstrap CI */
  diff: number
  diffLo: number
  diffHi: number
}}

/** Per corruption: level 0 (clean) then levels 1-4. `clean` has one row. */
export const SPIKES_POPULATION: Record<SpikesKind, SpikesConditionStats[]> = {ts(population)}
"""
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    print(f"\nwrote {out_path}")

    json_path = os.path.join(DATA, "demo_population.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump({"n": n, "population": population, "bank": bank,
                   "classes": CLASS_NAMES}, f, indent=1)
    print(f"wrote {json_path}")


if __name__ == "__main__":
    out = DEFAULT_OUT
    if "--out" in sys.argv:
        out = sys.argv[sys.argv.index("--out") + 1]
    main(out)
